apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-data
  labels:
    app: events-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-data
  template:
    metadata:
      labels:
        app: events-data
    spec:
      containers:
      - name: events-data
        image: jayrajendran123/market-app-int:v1.0.0
        env:
          name: PORT
          value: "8083"
        ports:
        - containerPort: 8083
          name: "events-port"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.1"
        livenessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 60

apiVersion: v1
kind: Service
metadata: 
  name: events-data-service
spec: 
  ports: 
    -   port: 8083
        protocol: TCP
        targetPort: 8888
  selector: 
    app: events-data
  type: ClusterIP